### PR TITLE
feat: add to_llvm_ir and lambdify

### PR DESCRIPTION
**Pull request by oscarbenjamin**
Adds the lambdify functions based on llvmlite to simplecas.

Quick benchmark with a large expression. This is SymEngine:
```python
In [10]: from symengine import *

In [11]: x = symbols('x')

In [12]: %time e = sin(sin(sin(sin(sin(sin(sin(x))))))).diff(x, 10)
CPU times: user 928 ms, sys: 8 ms, total: 936 ms
Wall time: 934 ms

In [13]: %time f = lambdify([x], [e], backend='llvm')
CPU times: user 35.8 s, sys: 168 ms, total: 36 s
Wall time: 35.9 s

In [14]: %time f(1)
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 416 µs
Out[14]: array(55578.02833128)

In [15]: %timeit f(1)
88.9 µs ± 898 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
This is protosym:
```python
In [16]: from protosym.simplecas import *

In [17]: x = Symbol('x')

In [18]: %time e = sin(sin(sin(sin(sin(sin(sin(x))))))).diff(x, 10)
CPU times: user 168 ms, sys: 4 ms, total: 172 ms
Wall time: 174 ms

In [19]: %time f = lambdify([x], e)
CPU times: user 208 ms, sys: 4 ms, total: 212 ms
Wall time: 214 ms

In [20]: %time f(1)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 47.4 µs
Out[20]: 55578.028331281705

In [21]: %timeit f(1)
2.32 µs ± 16.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
Every part is faster in protosym:

1. Creating and differentiating the expression.
2. Calling lambdify.
3. Calling the lambdified function.

With smaller expressions SymEngine is faster for the first two steps but the timings are also quite close. The lambdified function always seems to be faster with protosym though which I think comes from building the function out of the graph form.

SymEngine (small expression):
```python
In [1]: from symengine import *

In [2]: x = Symbol('x')

In [3]: %time e = sin(sin(sin(x))).diff(x)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 244 µs

In [4]: %time f = lambdify([x], [e], backend='llvm')
CPU times: user 8 ms, sys: 0 ns, total: 8 ms
Wall time: 11.7 ms

In [5]: %time f(1)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 122 µs
Out[5]: array(0.26450827)

In [6]: %timeit f(1)
11.2 µs ± 45.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
```
Then protosym:
```python
In [10]: from protosym.simplecas import *

In [11]: x = Symbol('x')

In [12]: %time e = sin(sin(sin(x))).diff(x)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 749 µs

In [13]: %time f = lambdify([x], e)
CPU times: user 44 ms, sys: 4 ms, total: 48 ms
Wall time: 46.2 ms

In [14]: %time f(1)
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 42.4 µs
Out[14]: 0.26450827039595814

In [15]: %timeit f(1)
875 ns ± 1.93 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

### CODE REVIEW

**Comment by brocksam** [comment]
The graph form is essentially the CSEd evaluation trace so this is not unexpected, but is still very nice to see!

**Comment by oscarbenjamin** [comment]
> The graph form is essentially the CSEd evaluation trace

I wondered whether LLVM would apply CSE and optimise the expression so that it works out the same either way. I'm guessing from the time taken by SymEngine's lambdify that it recurses the full tree but I still thought that LLVM itself might simplify it down afterwards.

**Comment by oscarbenjamin** [comment]
The expression that protosym sends to LLVM probably has a lot of redundant things like `1*1*1*x` or `-1*-1*x` etc but it's possible that LLVM can more easily optimise those away (implying that it would be a waste of time for protosym to attempt the same).

**Comment by oscarbenjamin** [comment]
With this lambdify function we're not that far off the speed of numpy:
```python
In [13]: from protosym.simplecas import *

In [14]: import numpy as np

In [15]: f = lambdify([x], sin(sin(sin(sin(sin(x))))))

In [16]: vals = np.linspace(0, 10, 1000)

In [17]: %time ok = [f(v) for v in vals]
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 1.91 ms

In [18]: %timeit ok = [f(v) for v in vals]
861 µs ± 3.69 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

In [19]: %time ok = np.sin(np.sin(np.sin(np.sin(np.sin(vals)))))
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 587 µs

In [20]: %timeit ok = np.sin(np.sin(np.sin(np.sin(np.sin(vals)))))
103 µs ± 281 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
```
That implies that the whole concept of needing to vectorise can be reconsidered to some extent. Perhaps it would be good to compare these timings not just with SymEngine but also numpy, numexpr, numba, ...

**Comment by brocksam** [comment]
My knowledge of LLVM is very limited so take the following with a pinch of salt.

As far as I'm aware, LLVM is able to do optimisation passes at multiple points in the compilation chain. Including optimisation passes on the IR. So it would definitely be possible for LLVM to do those simplifications to remove the redundant operations in your examples above. But whether llvmlite is automatically applying these optimisation I wouldn't know. I assume most, if not all, optimisations would be opt in. I'd also be surprised if we were able to do those simple optimisation in SimpleCAS more efficiently than LLVM is able to.

**Comment by brocksam** [comment]
> Perhaps it would be good to compare these timings not just with SymEngine but also numpy, numexpr, numba, ...

I agree. Perhaps this could motivate a `benchmarks/` directory to formalise some of these cases that you're showcasing in these PRs. I think pytest-benchmark would be good for this, especially as we're already using pytest, because it's main use case is creating groups of benchmarks that do the same thing and comparing between them. If you agree I could start putting this together?

**Comment by brocksam** [comment]
After making some formal benchmarks, this might be worth investigating a bit: https://llvmlite.readthedocs.io/en/latest/user-guide/binding/optimization-passes.html.

Regarding vectorisation, it'd say that the 4-8 speed difference versus vectorised NumPy functions is still a considerable amount and so it would still be worth looking into.

I'd also be interested to compare that NumPy benchmark to one using a NumPy-based `Evaluator`.

**Comment by oscarbenjamin** [comment]
> I assume most, if not all, optimisations would be opt in.

This is a good point. The difference in timings between lambdify for SymEngine and protosym are (I think) down to the tree vs graph representation. The difference in timing for calling the lambdified function might actually be due to the difference in optimisations that are being applied by LLVM. I have not taken time to investigate the optimisation options provided by LLVM/llvmlite and the code here is really just adapted from the corresponding SymPy code.

Another thing is that most of the time in protosym's `lambdify` is actually spent by llvmlite parsing the code. That's because we're passing the textual form of LLVM IR as a string but actually llvmlite provides APIs that can more directly construct the in-memory form of the IR.

> Perhaps this could motivate a `benchmarks/` directory to formalise some of these cases that you're showcasing in these PRs.

Yes, I've been thinking the same.

> I think pytest-benchmark would be good for this, especially as we're already using pytest, because it's main use case is creating groups of benchmarks that do the same thing and comparing between them. If you agree I could start putting this together?

Yes, that would be great. I'm not sure yet if I think that pytest-benchmark is the best tool (because I don't know how it works!) but putting together benchmarks is absolutely worthwhile. I had a look at pytest-benchmark at some point and it looked better than asv for more basic usage.

Ideally we would have benchmarks somehow run in CI and then get published to a website somewhere or something like that...

The thing that most benchmark tools don't do very well as far as I know is comparisons between different software. What I would really like is to have a website (generated from CI) that gives timings for different options with different software for equivalent tasks like:

- Differentiate `sin(sin(..., x))` n times:
   - Plot of timings for sympy vs SymEngine vs Maxima vs Symbolics.jl
- Differentiate `sin(sin(..., x))` and then evaluate the result many times for different values of x:
   - Plot of timings for sympy vs SymEngine vs Maxima vs Symbolics.jl etc

**Comment by oscarbenjamin** [comment]
> Regarding vectorisation, it'd say that the 4-8 speed difference versus vectorised NumPy functions is still a considerable amount and so it would still be worth looking into.

Agreed. There are several options though. Currently numexpr is faster than numpy for complicated expressions because it avoids creating temporary arrays. We can probably achieve the same sort of benefit here.

Another factor is most likely the use of SIMD. In fact that might be the primary difference because you would expect SIMD to give a ~4x speedup. The LLVM sin and cos "intrinsics" can be applied to *vectors* of floats which is I think how we would gain use of SIMD.

> I'd also be interested to compare that NumPy benchmark to one using a NumPy-based `Evaluator`.

Yes, something like that is needed.

**Comment by oscarbenjamin** [comment]
> After making some formal benchmarks, this might be worth investigating a bit: https://llvmlite.readthedocs.io/en/latest/user-guide/binding/optimization-passes.html.

Looks like our messages crossed paths. Yes, in fact I'll give that a read now!

**Comment by oscarbenjamin** [comment]
> I'm not sure yet if I think that pytest-benchmark is the best tool

Actually it is definitely worth having. All the other stuff I said about benchmarks is sort of orthogonal to just wanting something that we can use to easily compare changes in the codebase which is what pytest-benchmark can provide.

If you're up for adding that then please do!

**Comment by oscarbenjamin** [comment]
> > After making some formal benchmarks, this might be worth investigating a bit: https://llvmlite.readthedocs.io/en/latest/user-guide/binding/optimization-passes.html.

I don't see anything about CSE there. Maybe there is something somewhere else...

**Review by brocksam — APPROVED** [review]
This looks good!

I will be interested to compare this to a version using llvmlite's [IR builder API](https://llvmlite.readthedocs.io/en/latest/user-guide/ir/ir-builder.html).

**Comment by oscarbenjamin** [comment]
> I will be interested to compare this to a version using llvmlite's [IR builder API](https://llvmlite.readthedocs.io/en/latest/user-guide/ir/ir-builder.html).

Yes, I think really that should be used. It is good to be able to output the text form of the IR but that should not be used directly in lambdify.

The example here shows that it should not be too difficult to make something using that:
https://llvmlite.readthedocs.io/en/latest/user-guide/ir/examples.html

Perhaps we should make it so that `to_llvm_ir()` produces the exact same text output as llvmlite's builder interface. Then it would be easy to test by comparing them.

**Comment by oscarbenjamin** [comment]
Thanks for the review!

**Pull request merged**
